USE exam_attendance;

-- Password hashes below are generated by Spring's BCryptPasswordEncoder for:
-- Admin@123 and Teacher@123
INSERT INTO users (username, password, role, enabled) VALUES
('admin1', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN', 1),
('teacher1', '$2a$10$7QJ0jI9f6LxQwW8Qwfg1zOPBXhM6fF95om5VXrDMAYA9Yg3.aCBXK', 'TEACHER', 1)
ON DUPLICATE KEY UPDATE username = VALUES(username);

INSERT INTO teachers (teacher_code, name, subject, user_id)
SELECT 'TCH-101', 'Dr. A. Sharma', 'Data Structures', u.id
FROM users u WHERE u.username = 'teacher1'
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO students (scholar_number, name, enrollment_number, department, section) VALUES
('SCH001', 'Riya Verma', 'ENR001', 'CSE', 'A'),
('SCH002', 'Arjun Das', 'ENR002', 'CSE', 'A'),
('SCH003', 'Nisha Sen', 'ENR003', 'ECE', 'B'),
('SCH004', 'Karan Iyer', 'ENR004', 'ME', 'C')
ON DUPLICATE KEY UPDATE
name = VALUES(name),
enrollment_number = VALUES(enrollment_number),
department = VALUES(department),
section = VALUES(section);
